// <auto-generated />
using System;
using BookstoreApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookstoreApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212012508_v3")]
    partial class v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookstoreApplication.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Birthday");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "British writer and journalist.",
                            DateOfBirth = new DateTime(1903, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "George Orwell"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "English novelist known for romantic fiction.",
                            DateOfBirth = new DateTime(1775, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Jane Austen"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "British author best known for Harry Potter series.",
                            DateOfBirth = new DateTime(1965, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "J.K. Rowling"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "American writer and humorist.",
                            DateOfBirth = new DateTime(1835, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Mark Twain"
                        },
                        new
                        {
                            Id = 5,
                            Biography = "Russian novelist, known for War and Peace.",
                            DateOfBirth = new DateTime(1828, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Leo Tolstoy"
                        });
                });

            modelBuilder.Entity("BookstoreApplication.Models.AuthorAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<int>("AwardId")
                        .HasColumnType("integer");

                    b.Property<int>("YearAwarded")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("AwardId");

                    b.ToTable("AuthorAwardBridge", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            AwardId = 1,
                            YearAwarded = 1950
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            AwardId = 2,
                            YearAwarded = 1955
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            AwardId = 1,
                            YearAwarded = 1805
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            AwardId = 3,
                            YearAwarded = 1810
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            AwardId = 3,
                            YearAwarded = 2000
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            AwardId = 2,
                            YearAwarded = 2001
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 3,
                            AwardId = 4,
                            YearAwarded = 2020
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 4,
                            AwardId = 1,
                            YearAwarded = 1870
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 4,
                            AwardId = 3,
                            YearAwarded = 1880
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 4,
                            AwardId = 2,
                            YearAwarded = 1890
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 5,
                            AwardId = 1,
                            YearAwarded = 1900
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 5,
                            AwardId = 4,
                            YearAwarded = 1910
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 1,
                            AwardId = 4,
                            YearAwarded = 1960
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 2,
                            AwardId = 2,
                            YearAwarded = 1820
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 5,
                            AwardId = 3,
                            YearAwarded = 1905
                        });
                });

            modelBuilder.Entity("BookstoreApplication.Models.Award", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StartedYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Awards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Prestigious national award",
                            Name = "Literary Prize A",
                            StartedYear = 1950
                        },
                        new
                        {
                            Id = 2,
                            Description = "International recognition",
                            Name = "International Book Award",
                            StartedYear = 1965
                        },
                        new
                        {
                            Id = 3,
                            Description = "Award voted by readers",
                            Name = "Readers' Choice",
                            StartedYear = 1990
                        },
                        new
                        {
                            Id = 4,
                            Description = "For lifetime contribution to literature",
                            Name = "Lifetime Achievement",
                            StartedYear = 2000
                        });
                });

            modelBuilder.Entity("BookstoreApplication.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PublisherId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            ISBN = "9780451524935",
                            PageCount = 328,
                            PublishedDate = new DateTime(1949, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            ISBN = "9780451526342",
                            PageCount = 112,
                            PublishedDate = new DateTime(1945, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "Animal Farm"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            ISBN = "9780141439518",
                            PageCount = 432,
                            PublishedDate = new DateTime(1813, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            ISBN = "9780141439587",
                            PageCount = 474,
                            PublishedDate = new DateTime(1815, 12, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 3,
                            Title = "Emma"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            ISBN = "9780747532699",
                            PageCount = 223,
                            PublishedDate = new DateTime(1997, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            Title = "Harry Potter and the Philosopher's Stone"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            ISBN = "9780747538493",
                            PageCount = 251,
                            PublishedDate = new DateTime(1998, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            Title = "Harry Potter and the Chamber of Secrets"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 3,
                            ISBN = "9780747542155",
                            PageCount = 317,
                            PublishedDate = new DateTime(1999, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            Title = "Harry Potter and the Prisoner of Azkaban"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 4,
                            ISBN = "9780142437179",
                            PageCount = 366,
                            PublishedDate = new DateTime(1884, 12, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 3,
                            Title = "Adventures of Huckleberry Finn"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 4,
                            ISBN = "9780143039563",
                            PageCount = 274,
                            PublishedDate = new DateTime(1876, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "The Adventures of Tom Sawyer"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 5,
                            ISBN = "9780140447934",
                            PageCount = 1225,
                            PublishedDate = new DateTime(1869, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 3,
                            Title = "War and Peace"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 5,
                            ISBN = "9780143035008",
                            PageCount = 864,
                            PublishedDate = new DateTime(1877, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 3,
                            Title = "Anna Karenina"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 5,
                            ISBN = "9780553210354",
                            PageCount = 86,
                            PublishedDate = new DateTime(1886, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "The Death of Ivan Ilyich"
                        });
                });

            modelBuilder.Entity("BookstoreApplication.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "80 Strand, London",
                            Name = "Penguin Books",
                            Website = "https://penguin.co.uk"
                        },
                        new
                        {
                            Id = 2,
                            Address = "50 Bedford Square, London",
                            Name = "Bloomsbury",
                            Website = "https://www.bloomsbury.com"
                        },
                        new
                        {
                            Id = 3,
                            Address = "New York, USA",
                            Name = "Vintage Books",
                            Website = "https://www.vintagebooks.com"
                        });
                });

            modelBuilder.Entity("BookstoreApplication.Models.AuthorAward", b =>
                {
                    b.HasOne("BookstoreApplication.Models.Author", "Author")
                        .WithMany("AuthorAwards")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookstoreApplication.Models.Award", "Award")
                        .WithMany("AuthorAwards")
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Award");
                });

            modelBuilder.Entity("BookstoreApplication.Models.Book", b =>
                {
                    b.HasOne("BookstoreApplication.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookstoreApplication.Models.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("BookstoreApplication.Models.Author", b =>
                {
                    b.Navigation("AuthorAwards");
                });

            modelBuilder.Entity("BookstoreApplication.Models.Award", b =>
                {
                    b.Navigation("AuthorAwards");
                });
#pragma warning restore 612, 618
        }
    }
}
